### ISSUE TITLE
Mixed up colors in screenshots

### ISSUE THREAD

**Issue by CoolCoderGuy** [TheMiningTeamYT/TI84CE-Blocks-3D#10]
When I take screen shots to my usb storage it works but the images always come out with all the colors wrong. I linked an example screenshot.
![2327-001](https://github.com/TheMiningTeamYT/TICraft/assets/158845593/6608c7aa-43db-436c-92f0-bc4d56418be8)

**Comment by CoolCoderGuy** [comment]
also the brightness of the image looks a little odd compared to the other screen shots of the game I've seen.

**Comment by TheMiningTeamYT** [comment]
My bad. This is a bug I fixed like a week ago that I just forgot to ever commit to the repo.
If you download the latest version and try it again, it should work now.

**Comment by CoolCoderGuy** [comment]
Oh cool. Btw do I need to redownload the texture packs when a new version comes out or just the .8xp file?

**Comment by TheMiningTeamYT** [comment]
Sometimes you'll need to re-download the texture packs, but not this time.
I'll state in the release notes if you need to re-download the texture packs. (Or at least try to remember to do so.)

**Comment by CoolCoderGuy** [comment]
Ok sounds good 👍 thanks for the help
