### ISSUE TITLE
Just a question, can you list the controls in more detail I kind of get them but I think I need more information

### ISSUE THREAD

**Issue by ghost** [TheMiningTeamYT/TI84CE-Blocks-3D#5]
I was wondering if you could list the controls and maybe put them into the readme I see from the screenshots you can move you rcamera angle but i can't figure out how.
If you could let me know that would be great!

**Comment by TheMiningTeamYT** [comment]
I'll put them in the read me when I have time.
The camera rotation controls are:
Prgm: Rotate up
Cos: Rotate down
Sin: Rotate Left
Tan: Rotate right

**Comment by TheMiningTeamYT** [comment]
Alright, I've now update the readme with _all_ of the controls.
