### ISSUE TITLE
Weird clipping artifact things in the corner of the screen.

### ISSUE THREAD

**Issue by CommentedNewline** [TheMiningTeamYT/TI84CE-Blocks-3D#8]
![clipok](https://github.com/TheMiningTeamYT/TICraft/assets/135905581/5e6d63c9-4f87-43e5-89fa-ba69b110b28a)
This is one I could replicate. They can be much bigger, taking up 1/8 of the render FOV.

To replicate: rotate the camera using sin/tan while being a few units of the ground until clipping appears.

**Comment by CommentedNewline** [comment]
![clipworse](https://github.com/TheMiningTeamYT/TICraft/assets/135905581/64f8ae01-67da-4576-bc88-834d8647d927)
Other one

**Comment by TheMiningTeamYT** [comment]
I've been working on this issue the last few days and, although it's not fully fixed, I think it's better now. Go ahead and try the latest version of TICRAFT and lemme know how that works for you! (BTW, quick question: did you happen to use TICraft's screenshot feature for these screenshots? Just curious. Although I don't believe I documented it anywhere until I added it to the readme today...)

**Comment by CommentedNewline** [comment]
Yeah it's much better. It's mostly gone.
I'm not going to close it but you can if you want

No I just used CEMU because I lost my flash drive adapter. (But I knew of the feature because I smashed every button on my calc and it popped up. )
